export const OPEN_NAVIGATION = "OPEN_NAVIGATION";

//product
export const PRODUCT_LOADING = "PRODUCT_LOADING";
export const PRODUCT_LOAD_SUCCESS = "PRODUCT_LOAD_SUCCESS";
export const PRODUCT_LOAD_ERROR = "PRODUCT_LOAD_ERROR";

//getProductDetail
export const PRODUCTDETAIL_LOADING = "PRODUCTDETAIL_LOADING";
export const GET_PRODUCTDETAIL_SUCCESS = "GET_PRODUCTDETAIL_SUCCESS";
export const GET_PRODUCTDETAIL_ERROR = "GET_PRODUCTDETAIL_ERROR";

//searchProduct
export const SEARCHPRODUCT_LOADING = "SEARCHPRODUCT_LOADING";
export const SEARCHPRODUCT_SUCCESS = "SEARCHPRODUCT_SUCCESS";
export const SEARCHPRODUCT_ERROR = "SEARCHPRODUCT_ERROR";

//cart
export const ADD_TO_CART = "ADD_TO_CART";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTIT = "DECREASE_QUANTITY";
export const CLEAR_CART = "CLEAR_CART";
//login
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

//logout
export const LOGOUT = "LOGOUT";

//register
export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";

//filter products
export const FILTER_BY_PRICE = "FILTER_BY_PRICE";

export const FILTER_BY_SIZE = "FILTER_BY_SIZE";
export const FILTER_BY_BRAND = "FILTER_BY_BRAND";
export const FILTER_BY_POSITION = "FILTER_BY_POSITION";
export const FILTER_BY_RATING = "FILTER_BY_RATING";
